// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef MRNOTEDATA_ODB_HXX
#define MRNOTEDATA_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "mrnotedata.h"

#include "mrarticlemetadata-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // MRNoteData
  //
  template <>
  struct class_traits< ::MRNoteData >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::MRNoteData >
  {
    public:
    typedef ::MRNoteData object_type;
    typedef ::MRNoteData* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // MRNoteData
  //
  template <typename A>
  struct pointer_query_columns< ::MRNoteData, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // index
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    index_type_;

    static const index_type_ index;

    // title
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    title_type_;

    static const title_type_ title;

    // text
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    text_type_;

    static const text_type_ text;

    // path
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    path_type_;

    static const path_type_ path;

    // note
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    note_type_;

    static const note_type_ note;

    // article
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    article_type_;

    static const article_type_ article;
  };

  template <typename A>
  const typename pointer_query_columns< ::MRNoteData, id_sqlite, A >::id_type_
  pointer_query_columns< ::MRNoteData, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::MRNoteData, id_sqlite, A >::index_type_
  pointer_query_columns< ::MRNoteData, id_sqlite, A >::
  index (A::table_name, "\"index\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::MRNoteData, id_sqlite, A >::title_type_
  pointer_query_columns< ::MRNoteData, id_sqlite, A >::
  title (A::table_name, "\"title\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::MRNoteData, id_sqlite, A >::text_type_
  pointer_query_columns< ::MRNoteData, id_sqlite, A >::
  text (A::table_name, "\"text\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::MRNoteData, id_sqlite, A >::path_type_
  pointer_query_columns< ::MRNoteData, id_sqlite, A >::
  path (A::table_name, "\"path\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::MRNoteData, id_sqlite, A >::note_type_
  pointer_query_columns< ::MRNoteData, id_sqlite, A >::
  note (A::table_name, "\"note\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::MRNoteData, id_sqlite, A >::article_type_
  pointer_query_columns< ::MRNoteData, id_sqlite, A >::
  article (A::table_name, "\"article\"", 0);

  template <>
  class access::object_traits_impl< ::MRNoteData, id_sqlite >:
    public access::object_traits< ::MRNoteData >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // _id
      //
      long long _id_value;
      bool _id_null;

      // _index
      //
      long long _index_value;
      bool _index_null;

      // _title
      //
      details::buffer _title_value;
      std::size_t _title_size;
      bool _title_null;

      // _text
      //
      details::buffer _text_value;
      std::size_t _text_size;
      bool _text_null;

      // _path
      //
      details::buffer _path_value;
      std::size_t _path_size;
      bool _path_null;

      // _note
      //
      details::buffer _note_value;
      std::size_t _note_size;
      bool _note_null;

      // _article
      //
      long long _article_value;
      bool _article_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct article_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::MRNoteData, id_common >:
    public access::object_traits_impl< ::MRNoteData, id_sqlite >
  {
  };

  // MRNoteData
  //
  template <>
  struct alias_traits<
    ::MRArticleMetaData,
    id_sqlite,
    access::object_traits_impl< ::MRNoteData, id_sqlite >::article_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::MRNoteData, id_sqlite >
  {
    // article
    //
    typedef
    odb::alias_traits<
      ::MRArticleMetaData,
      id_sqlite,
      access::object_traits_impl< ::MRNoteData, id_sqlite >::article_tag>
    article_alias_;
  };

  template <typename A>
  struct query_columns< ::MRNoteData, id_sqlite, A >:
    query_columns_base< ::MRNoteData, id_sqlite >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // index
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    index_type_;

    static const index_type_ index;

    // title
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    title_type_;

    static const title_type_ title;

    // text
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    text_type_;

    static const text_type_ text;

    // path
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    path_type_;

    static const path_type_ path;

    // note
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    note_type_;

    static const note_type_ note;

    // article
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    article_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::MRArticleMetaData,
        id_sqlite,
        article_alias_ > >
    article_pointer_type_;

    struct article_type_: article_pointer_type_, article_column_type_
    {
      article_type_ (const char* t, const char* c, const char* conv)
        : article_column_type_ (t, c, conv)
      {
      }
    };

    static const article_type_ article;
  };

  template <typename A>
  const typename query_columns< ::MRNoteData, id_sqlite, A >::id_type_
  query_columns< ::MRNoteData, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::MRNoteData, id_sqlite, A >::index_type_
  query_columns< ::MRNoteData, id_sqlite, A >::
  index (A::table_name, "\"index\"", 0);

  template <typename A>
  const typename query_columns< ::MRNoteData, id_sqlite, A >::title_type_
  query_columns< ::MRNoteData, id_sqlite, A >::
  title (A::table_name, "\"title\"", 0);

  template <typename A>
  const typename query_columns< ::MRNoteData, id_sqlite, A >::text_type_
  query_columns< ::MRNoteData, id_sqlite, A >::
  text (A::table_name, "\"text\"", 0);

  template <typename A>
  const typename query_columns< ::MRNoteData, id_sqlite, A >::path_type_
  query_columns< ::MRNoteData, id_sqlite, A >::
  path (A::table_name, "\"path\"", 0);

  template <typename A>
  const typename query_columns< ::MRNoteData, id_sqlite, A >::note_type_
  query_columns< ::MRNoteData, id_sqlite, A >::
  note (A::table_name, "\"note\"", 0);

  template <typename A>
  const typename query_columns< ::MRNoteData, id_sqlite, A >::article_type_
  query_columns< ::MRNoteData, id_sqlite, A >::
  article (A::table_name, "\"article\"", 0);
}

#include "mrnotedata-odb.ixx"

#include <odb/post.hxx>

#endif // MRNOTEDATA_ODB_HXX
